name: Publish Docker image

on:
  push:
    branches: [ development ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PW }}
          repository: castudl/clusive
          add_git_labels: true
          tag_with_ref: true
          tags: ${{ env.GITHUB_SHA }}
      - name: Update QA
        uses: wei/curl@v1
        with:
          args: -Lis -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}?tag=${{ env.GITHUB_SHA }}"
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@v1.1.0
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: New build deployed to https://clusive.qa.cast.org
