name: Publish Docker image

on:
  push:
    branches: [ development ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PW }}
          repository: castudl/clusive
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
